// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_organizations_upload_organization_image = {
    file: (Blob | File);
};

export type Body_users_upload_image = {
    file: (Blob | File);
};

export type Corner = {
    /**
     * X coordinate of the corner
     */
    x: number;
    /**
     * Y coordinate of the corner
     */
    y: number;
};

export type DeviceCreate = {
    name: string;
    description?: (string | null);
    model: string;
    category: string;
    serial_number: string;
    mac_address: string;
    image?: (string | null);
    /**
     * Whether the device is enabled
     */
    enabled?: boolean;
};

export type DevicePublic = {
    name: string;
    description?: (string | null);
    model: string;
    category: string;
    serial_number: string;
    mac_address: string;
    image?: (string | null);
    /**
     * Whether the device is enabled
     */
    enabled?: boolean;
    uid: string;
    owner_id: string;
};

export type DeviceReading = {
    /**
     * Unique identifier for the reading batch
     */
    uid: string;
    /**
     * Resolution of readings, e.g., '1hour', '1min', '1day'
     */
    resolution: string;
    /**
     * ISO 8601 formatted start time
     */
    start_time: string;
    /**
     * ISO 8601 formatted end time
     */
    end_time: string;
    /**
     * Name of the sensor or endpoint being measured
     */
    endpoint_name: string;
    /**
     * Type of measurement, e.g., 'energy', 'temperature', 'CO2'
     */
    measure_type: string;
    /**
     * Units of measurement, e.g., 'Wh', 'celsius', 'ppm', 'lumens'
     */
    units: string;
    /**
     * List of timestamped readings
     */
    readings: Array<Reading>;
};

export type DeviceReadingsPublic = {
    /**
     * List of device readings
     */
    data: Array<DeviceReading>;
    /**
     * Total number of device readings
     */
    count: number;
};

export type DevicesPublic = {
    data: Array<DevicePublic>;
    count: number;
};

export type DeviceUpdate = {
    name?: (string | null);
    description?: (string | null);
    model?: (string | null);
    category: string;
    serial_number?: (string | null);
    mac_address?: (string | null);
    image?: (string | null);
    enabled?: (boolean | null);
    owner_id?: (string | null);
};

export type Floorplan_Input = {
    /**
     * Dictionary of corner UUIDs to corner coordinates
     */
    corners: {
        [key: string]: Corner;
    };
    /**
     * List of walls connecting corners
     */
    walls: Array<Wall>;
    /**
     * Wall textures (legacy field)
     */
    wallTextures?: Array<unknown>;
    /**
     * Floor textures (legacy field)
     */
    floorTextures?: {
        [key: string]: unknown;
    };
    /**
     * New floor textures mapping
     */
    newFloorTextures?: {
        [key: string]: FloorTexture;
    };
};

export type Floorplan_Output = {
    /**
     * Dictionary of corner UUIDs to corner coordinates
     */
    corners: {
        [key: string]: Corner;
    };
    /**
     * List of walls connecting corners
     */
    walls: Array<Wall>;
    /**
     * Wall textures (legacy field)
     */
    wallTextures?: Array<unknown>;
    /**
     * Floor textures (legacy field)
     */
    floorTextures?: {
        [key: string]: unknown;
    };
    /**
     * New floor textures mapping
     */
    newFloorTextures?: {
        [key: string]: FloorTexture;
    };
};

export type FloorTexture = {
    /**
     * URL/path to the floor texture file
     */
    url: string;
    /**
     * Scale factor for the floor texture
     */
    scale: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    description?: (string | null);
    address?: (string | null);
    image?: (string | null);
    parent_id?: (string | null);
};

export type OrganizationPublic = {
    name: string;
    description?: (string | null);
    address?: (string | null);
    image?: (string | null);
    uid: string;
    parent_id: string;
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    description?: (string | null);
    address?: (string | null);
    image?: (string | null);
    parent_id?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Reading = {
    /**
     * ISO 8601 formatted timestamp
     */
    timestamp: string;
    /**
     * Measured value at the given timestamp
     */
    value: number;
};

export type SceneCreate = {
    /**
     * Floorplan configuration with corners, walls, and textures
     */
    floorplan: Floorplan_Input;
    /**
     * List of items placed in the scene
     */
    items?: Array<SceneItem>;
    /**
     * UUID of the organization that owns this scene
     */
    organization_id: string;
    /**
     * Label/name for the scene
     */
    label?: string;
};

export type SceneItem = {
    /**
     * Name of the item
     */
    item_name: string;
    /**
     * Type identifier for the item
     */
    item_type: number;
    /**
     * URL/path to the 3D model file
     */
    model_url: string;
    /**
     * X position in the scene
     */
    xpos: number;
    /**
     * Y position in the scene
     */
    ypos: number;
    /**
     * Z position in the scene
     */
    zpos: number;
    /**
     * Rotation angle in degrees
     */
    rotation: number;
    /**
     * Scale factor on X axis
     */
    scale_x?: number;
    /**
     * Scale factor on Y axis
     */
    scale_y?: number;
    /**
     * Scale factor on Z axis
     */
    scale_z?: number;
    /**
     * Whether the item is fixed in position
     */
    fixed?: boolean;
};

export type ScenePublic = {
    /**
     * Floorplan configuration with corners, walls, and textures
     */
    floorplan: Floorplan_Output;
    /**
     * List of items placed in the scene
     */
    items?: Array<SceneItem>;
    /**
     * UUID of the organization that owns this scene
     */
    organization_id: string;
    /**
     * Label/name for the scene
     */
    label?: string;
    uid: string;
};

export type ScenesPublic = {
    data: Array<ScenePublic>;
    count: number;
};

export type SceneUpdate = {
    /**
     * Updated floorplan configuration
     */
    floorplan?: (Floorplan_Input | null);
    /**
     * Updated list of items in the scene
     */
    items?: (Array<SceneItem> | null);
    /**
     * Updated organization ID
     */
    organization_id?: (string | null);
    /**
     * Updated label/name for the scene
     */
    label?: (string | null);
};

export type StatusesPublic = {
    data: Array<StatusPublic>;
    count: number;
};

export type StatusPublic = {
    uid: string;
    device_name: string;
    status: string;
    battery_level: number;
    coordinates_x?: (number | null);
    coordinates_y?: (number | null);
    level?: (number | null);
    task_id?: (string | null);
    error_code?: (number | null);
    last_connection?: (string | null);
};

export type TaskCreate = {
    /**
     * Unique device identifier
     */
    device_uid: string;
    /**
     * Descriptive name of the task
     */
    task_name: string;
    /**
     * Type of task, e.g., Delivery, Patrol
     */
    type: string;
    /**
     * Current task status, e.g., Running, Completed
     */
    status: string;
    /**
     * ISO 8601 formatted start time
     */
    start_time: string;
    end_time?: (string | null);
    /**
     * List of waypoints for the task
     */
    waypoints: Array<Waypoint>;
};

export type TaskPublic = {
    /**
     * Unique task identifier
     */
    uid: string;
    /**
     * Unique device identifier
     */
    device_uid: string;
    /**
     * Descriptive name of the task
     */
    task_name: string;
    /**
     * Type of task, e.g., Delivery, Patrol
     */
    type: string;
    /**
     * Current task status, e.g., Running, Completed
     */
    status: string;
    /**
     * ISO 8601 formatted start time
     */
    start_time: string;
    end_time?: (string | null);
    /**
     * List of waypoints for the task
     */
    waypoints: Array<Waypoint>;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type Texture = {
    /**
     * URL/path to the texture file
     */
    url: string;
    /**
     * Whether to stretch the texture
     */
    stretch: boolean;
    /**
     * Scale factor for the texture
     */
    scale: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    image?: (string | null);
    password: string;
    organization_id: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    image?: (string | null);
    id: string;
    organization_id: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    organization_id: (string | null);
    image?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    image?: (string | null);
    password?: (string | null);
    organization_id?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    organization_id?: (string | null);
    image?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Wall = {
    /**
     * UUID of the first corner
     */
    corner1: string;
    /**
     * UUID of the second corner
     */
    corner2: string;
    /**
     * Texture for the front side of the wall
     */
    frontTexture: Texture;
    /**
     * Texture for the back side of the wall
     */
    backTexture: Texture;
};

export type Waypoint = {
    /**
     * ISO 8601 formatted timestamp
     */
    timestamp: string;
    /**
     * X coordinate
     */
    coordinates_x: number;
    /**
     * Y coordinate
     */
    coordinates_y: number;
    level?: (number | null);
    /**
     * Optional waypoint label
     */
    label?: (string | null);
};

export type DevicesReadDevicesData = {
    limit?: number;
    skip?: number;
};

export type DevicesReadDevicesResponse = (DevicesPublic);

export type DevicesCreateDeviceData = {
    requestBody: DeviceCreate;
};

export type DevicesCreateDeviceResponse = (DevicePublic);

export type DevicesReadDevicesStatusData = {
    limit?: number;
    skip?: number;
};

export type DevicesReadDevicesStatusResponse = (StatusesPublic);

export type DevicesReadDeviceData = {
    id: string;
};

export type DevicesReadDeviceResponse = (DevicePublic);

export type DevicesUpdateDeviceData = {
    id: string;
    requestBody: DeviceUpdate;
};

export type DevicesUpdateDeviceResponse = (DevicePublic);

export type DevicesDeleteDeviceData = {
    id: string;
};

export type DevicesDeleteDeviceResponse = (Message);

export type DevicesGetDevicesOwnData = {
    limit?: number;
    ownerId: string;
    skip?: number;
};

export type DevicesGetDevicesOwnResponse = (DevicesPublic);

export type DevicesGetDeviceStatusData = {
    uid: string;
};

export type DevicesGetDeviceStatusResponse = (StatusPublic);

export type DevicesGetDeviceTasksData = {
    uid: string;
};

export type DevicesGetDeviceTasksResponse = (TasksPublic);

export type DevicesCreateDeviceTaskData = {
    requestBody: TaskCreate;
    uid: string;
};

export type DevicesCreateDeviceTaskResponse = (TaskPublic);

export type DevicesGetDeviceReadingsData = {
    resolution: string;
    uid: string;
};

export type DevicesGetDeviceReadingsResponse = (DeviceReadingsPublic);

export type DevicesGetFilteredDeviceReadingsData = {
    measureType: string;
    resolution: string;
    uid: string;
};

export type DevicesGetFilteredDeviceReadingsResponse = (DeviceReadingsPublic);

export type DevicesUpdateDeviceListResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    id: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    id: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    id: string;
};

export type OrganizationsDeleteOrganizationResponse = (Message);

export type OrganizationsReadChildOrganizationsData = {
    id: string;
};

export type OrganizationsReadChildOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsReadOrganizationScenesData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationScenesResponse = (ScenesPublic);

export type OrganizationsUploadOrganizationImageData = {
    formData: Body_organizations_upload_organization_image;
    id: string;
};

export type OrganizationsUploadOrganizationImageResponse = (OrganizationPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ScenesReadScenesData = {
    limit?: number;
    skip?: number;
};

export type ScenesReadScenesResponse = (ScenesPublic);

export type ScenesCreateSceneData = {
    requestBody: SceneCreate;
};

export type ScenesCreateSceneResponse = (ScenePublic);

export type ScenesReadSceneData = {
    sceneId: string;
};

export type ScenesReadSceneResponse = (ScenePublic);

export type ScenesUpdateSceneData = {
    requestBody: SceneUpdate;
    sceneId: string;
};

export type ScenesUpdateSceneResponse = (ScenePublic);

export type ScenesDeleteSceneData = {
    sceneId: string;
};

export type ScenesDeleteSceneResponse = (Message);

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    uid: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersUploadImageData = {
    formData: Body_users_upload_image;
};

export type UsersUploadImageResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);